language: python
sudo: true
python:
- '3.7'
install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda;
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pandas scikit-learn
  coverage
- source activate test-environment
- pip install joblib falconn nmslib pytest nose codecov
- python setup.py build
- python setup.py install
script:
- python setup.py test
- coverage run setup.py test
- coverage combine # required for multiprocessing
env:
  - CODECOV_TOKEN=5d0d5dd0-2e59-47b8-8a2b-dbdc0fbb4e4c  # only for private repo
after_success:
- codecov
cache:
# - apt
- pip
- ccache
- packages
- directories:
  - "$HOME/.cache/pip"
# safelist
branches:
  only:
  - master
  - develop
