dist: xenial
language: python
sudo: false

env:
  global:
  - CACHE_DIR="$HOME/virtualenv"
  - MINICONDA_DIR="$HOME/miniconda"
  - PYTHONIOENCODING=UTF8

python:
  - '3.7'
  - "3.8-dev"  # 3.8 development branch

install:
  - travis/install-conda.sh
  - export PATH="$PATH:$HOME/miniconda/bin"
  - hash -r
  - travis/install-pip.sh
  - python setup.py build
  - python setup.py install

before_script:
  - flake8 --exit-zero .

script:
  - python setup.py test
  - pytest --cov=hubness

after_success:
  - codecov --token=5d0d5dd0-2e59-47b8-8a2b-dbdc0fbb4e4c  # only for private repo

cache:
  - pip
  - ccache
  - packages
  - directories:
      - "$HOME/.cache/pip"
      - "$HOME/virtualenv"
      - "$HOME/miniconda"

branches:
  only:
  - master
  - develop
